// quiz/config/capitals.js
// 世界首都クイズ（埋め込みの静的データを使用）

window.QUIZ_CONFIG = {
  title: "World Capitals Quiz",
  subtitle: "Test your knowledge of world capitals",
  backLink: "/geography/",
  backLabel: "Geography",
  answerType: "choice",
  startLabel: "START",

  rangeMode: "single",
  rangeLabel: "地域",
  ranges: [
    { id: "all", label: "全世界" },
    { id: "asia", label: "アジア" },
    { id: "europe", label: "ヨーロッパ" },
    { id: "africa", label: "アフリカ" },
    { id: "americas", label: "アメリカ大陸" },
    { id: "oceania", label: "オセアニア" },
  ],
  countMode: "select",
  countDefault: 10,
  countOptions: [5, 10, 20, 30],

  async fetchData(selectedRanges, count) {
    const region = selectedRanges[0];
    const source = countries;
    const filtered =
      region === "all" ? source : source.filter((c) => c.region === region);
    const shuffled = window._quizShuffle(filtered);
    return shuffled.slice(0, parseInt(count));
  },

  formatQuestion(row) {
    return {
      text: row.country,
      imageUrl: `https://flagcdn.com/w320/${row.code}.png`,
      imageAlt: `Flag of ${row.country}`,
    };
  },

  formatCorrectLabel(row) {
    return row.capital;
  },

  buildDistractors(current, allData) {
    const source = countries;
    return window
      ._quizShuffle(source.filter((r) => r.capital !== current.capital))
      .slice(0, 3);
  },

  // 首都名と日本語名を両方表示する
  renderChoice(opt, i) {
    const country = countries.find((c) => c.capital === opt);
    const jp = country?.capitalJP ?? "";
    return `
      <span class="qz-choice__text">
        ${_esc(opt)}${jp ? `<br><small style="font-weight:400;color:var(--qz-text-sub);">${_esc(jp)}</small>` : ""}
      </span>
    `;
  },

  getCorrectValue: null,
  validate: null,
  onAnswer: null,
  extraRenderer: null,
  renderMistake: null,
};

function _esc(str) {
  return String(str ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/* 国データ（地域付き） */
const countries = [
  /* ===== ASIA（49）===== */
  {
    country: "Japan",
    capital: "Tokyo",
    capitalJP: "東京",
    code: "jp",
    region: "asia",
  },
  {
    country: "China",
    capital: "Beijing",
    capitalJP: "北京",
    code: "cn",
    region: "asia",
  },
  {
    country: "South Korea",
    capital: "Seoul",
    capitalJP: "ソウル",
    code: "kr",
    region: "asia",
  },
  {
    country: "North Korea",
    capital: "Pyongyang",
    capitalJP: "平壌",
    code: "kp",
    region: "asia",
  },
  {
    country: "Mongolia",
    capital: "Ulaanbaatar",
    capitalJP: "ウランバートル",
    code: "mn",
    region: "asia",
  },
  {
    country: "Taiwan",
    capital: "Taipei",
    capitalJP: "台北",
    code: "tw",
    region: "asia",
  },
  {
    country: "India",
    capital: "New Delhi",
    capitalJP: "ニューデリー",
    code: "in",
    region: "asia",
  },
  {
    country: "Pakistan",
    capital: "Islamabad",
    capitalJP: "イスラマバード",
    code: "pk",
    region: "asia",
  },
  {
    country: "Bangladesh",
    capital: "Dhaka",
    capitalJP: "ダッカ",
    code: "bd",
    region: "asia",
  },
  {
    country: "Sri Lanka",
    capital: "Sri Jayawardenepura Kotte",
    capitalJP: "スリ・ジャヤワルデネプラ・コッテ",
    code: "lk",
    region: "asia",
  },
  {
    country: "Nepal",
    capital: "Kathmandu",
    capitalJP: "カトマンズ",
    code: "np",
    region: "asia",
  },
  {
    country: "Bhutan",
    capital: "Thimphu",
    capitalJP: "ティンプー",
    code: "bt",
    region: "asia",
  },
  {
    country: "Myanmar",
    capital: "Naypyidaw",
    capitalJP: "ネピドー",
    code: "mm",
    region: "asia",
  },
  {
    country: "Thailand",
    capital: "Bangkok",
    capitalJP: "バンコク",
    code: "th",
    region: "asia",
  },
  {
    country: "Laos",
    capital: "Vientiane",
    capitalJP: "ビエンチャン",
    code: "la",
    region: "asia",
  },
  {
    country: "Cambodia",
    capital: "Phnom Penh",
    capitalJP: "プノンペン",
    code: "kh",
    region: "asia",
  },
  {
    country: "Vietnam",
    capital: "Hanoi",
    capitalJP: "ハノイ",
    code: "vn",
    region: "asia",
  },
  {
    country: "Malaysia",
    capital: "Kuala Lumpur",
    capitalJP: "クアラルンプール",
    code: "my",
    region: "asia",
  },
  {
    country: "Singapore",
    capital: "Singapore",
    capitalJP: "シンガポール",
    code: "sg",
    region: "asia",
  },
  {
    country: "Indonesia",
    capital: "Jakarta",
    capitalJP: "ジャカルタ",
    code: "id",
    region: "asia",
  },
  {
    country: "Philippines",
    capital: "Manila",
    capitalJP: "マニラ",
    code: "ph",
    region: "asia",
  },
  {
    country: "Brunei",
    capital: "Bandar Seri Begawan",
    capitalJP: "バンダルスリブガワン",
    code: "bn",
    region: "asia",
  },
  {
    country: "Iran",
    capital: "Tehran",
    capitalJP: "テヘラン",
    code: "ir",
    region: "asia",
  },
  {
    country: "Iraq",
    capital: "Baghdad",
    capitalJP: "バグダッド",
    code: "iq",
    region: "asia",
  },
  {
    country: "Israel",
    capital: "Jerusalem",
    capitalJP: "エルサレム",
    code: "il",
    region: "asia",
  },
  {
    country: "Jordan",
    capital: "Amman",
    capitalJP: "アンマン",
    code: "jo",
    region: "asia",
  },
  {
    country: "Lebanon",
    capital: "Beirut",
    capitalJP: "ベイルート",
    code: "lb",
    region: "asia",
  },
  {
    country: "Syria",
    capital: "Damascus",
    capitalJP: "ダマスカス",
    code: "sy",
    region: "asia",
  },
  {
    country: "Turkey",
    capital: "Ankara",
    capitalJP: "アンカラ",
    code: "tr",
    region: "asia",
  },
  {
    country: "Saudi Arabia",
    capital: "Riyadh",
    capitalJP: "リヤド",
    code: "sa",
    region: "asia",
  },
  {
    country: "Yemen",
    capital: "Sana'a",
    capitalJP: "サナア",
    code: "ye",
    region: "asia",
  },
  {
    country: "Oman",
    capital: "Muscat",
    capitalJP: "マスカット",
    code: "om",
    region: "asia",
  },
  {
    country: "United Arab Emirates",
    capital: "Abu Dhabi",
    capitalJP: "アブダビ",
    code: "ae",
    region: "asia",
  },
  {
    country: "Qatar",
    capital: "Doha",
    capitalJP: "ドーハ",
    code: "qa",
    region: "asia",
  },
  {
    country: "Kuwait",
    capital: "Kuwait City",
    capitalJP: "クウェート",
    code: "kw",
    region: "asia",
  },
  {
    country: "Bahrain",
    capital: "Manama",
    capitalJP: "マナーマ",
    code: "bh",
    region: "asia",
  },
  {
    country: "Kazakhstan",
    capital: "Astana",
    capitalJP: "アスタナ",
    code: "kz",
    region: "asia",
  },
  {
    country: "Uzbekistan",
    capital: "Tashkent",
    capitalJP: "タシケント",
    code: "uz",
    region: "asia",
  },
  {
    country: "Turkmenistan",
    capital: "Ashgabat",
    capitalJP: "アシガバート",
    code: "tm",
    region: "asia",
  },
  {
    country: "Kyrgyzstan",
    capital: "Bishkek",
    capitalJP: "ビシュケク",
    code: "kg",
    region: "asia",
  },
  {
    country: "Tajikistan",
    capital: "Dushanbe",
    capitalJP: "ドゥシャンベ",
    code: "tj",
    region: "asia",
  },
  {
    country: "Afghanistan",
    capital: "Kabul",
    capitalJP: "カブール",
    code: "af",
    region: "asia",
  },
  {
    country: "Georgia",
    capital: "Tbilisi",
    capitalJP: "トビリシ",
    code: "ge",
    region: "asia",
  },
  {
    country: "Armenia",
    capital: "Yerevan",
    capitalJP: "エレバン",
    code: "am",
    region: "asia",
  },
  {
    country: "Azerbaijan",
    capital: "Baku",
    capitalJP: "バクー",
    code: "az",
    region: "asia",
  },
  {
    country: "Timor-Leste",
    capital: "Dili",
    capitalJP: "ディリ",
    code: "tl",
    region: "asia",
  },
  {
    country: "Palestine",
    capital: "Ramallah",
    capitalJP: "ラマッラー",
    code: "ps",
    region: "asia",
  },

  /* ===== EUROPE（44）===== */
  {
    country: "United Kingdom",
    capital: "London",
    capitalJP: "ロンドン",
    code: "gb",
    region: "europe",
  },
  {
    country: "Ireland",
    capital: "Dublin",
    capitalJP: "ダブリン",
    code: "ie",
    region: "europe",
  },
  {
    country: "France",
    capital: "Paris",
    capitalJP: "パリ",
    code: "fr",
    region: "europe",
  },
  {
    country: "Germany",
    capital: "Berlin",
    capitalJP: "ベルリン",
    code: "de",
    region: "europe",
  },
  {
    country: "Spain",
    capital: "Madrid",
    capitalJP: "マドリード",
    code: "es",
    region: "europe",
  },
  {
    country: "Portugal",
    capital: "Lisbon",
    capitalJP: "リスボン",
    code: "pt",
    region: "europe",
  },
  {
    country: "Italy",
    capital: "Rome",
    capitalJP: "ローマ",
    code: "it",
    region: "europe",
  },
  {
    country: "Belgium",
    capital: "Brussels",
    capitalJP: "ブリュッセル",
    code: "be",
    region: "europe",
  },
  {
    country: "Netherlands",
    capital: "Amsterdam",
    capitalJP: "アムステルダム",
    code: "nl",
    region: "europe",
  },
  {
    country: "Luxembourg",
    capital: "Luxembourg",
    capitalJP: "ルクセンブルク",
    code: "lu",
    region: "europe",
  },
  {
    country: "Switzerland",
    capital: "Bern",
    capitalJP: "ベルン",
    code: "ch",
    region: "europe",
  },
  {
    country: "Austria",
    capital: "Vienna",
    capitalJP: "ウィーン",
    code: "at",
    region: "europe",
  },
  {
    country: "Denmark",
    capital: "Copenhagen",
    capitalJP: "コペンハーゲン",
    code: "dk",
    region: "europe",
  },
  {
    country: "Norway",
    capital: "Oslo",
    capitalJP: "オスロ",
    code: "no",
    region: "europe",
  },
  {
    country: "Sweden",
    capital: "Stockholm",
    capitalJP: "ストックホルム",
    code: "se",
    region: "europe",
  },
  {
    country: "Finland",
    capital: "Helsinki",
    capitalJP: "ヘルシンキ",
    code: "fi",
    region: "europe",
  },
  {
    country: "Iceland",
    capital: "Reykjavik",
    capitalJP: "レイキャヴィーク",
    code: "is",
    region: "europe",
  },
  {
    country: "Poland",
    capital: "Warsaw",
    capitalJP: "ワルシャワ",
    code: "pl",
    region: "europe",
  },
  {
    country: "Czech Republic",
    capital: "Prague",
    capitalJP: "プラハ",
    code: "cz",
    region: "europe",
  },
  {
    country: "Slovakia",
    capital: "Bratislava",
    capitalJP: "ブラチスラヴァ",
    code: "sk",
    region: "europe",
  },
  {
    country: "Hungary",
    capital: "Budapest",
    capitalJP: "ブダペスト",
    code: "hu",
    region: "europe",
  },
  {
    country: "Slovenia",
    capital: "Ljubljana",
    capitalJP: "リュブリャナ",
    code: "si",
    region: "europe",
  },
  {
    country: "Croatia",
    capital: "Zagreb",
    capitalJP: "ザグレブ",
    code: "hr",
    region: "europe",
  },
  {
    country: "Bosnia and Herzegovina",
    capital: "Sarajevo",
    capitalJP: "サラエヴォ",
    code: "ba",
    region: "europe",
  },
  {
    country: "Serbia",
    capital: "Belgrade",
    capitalJP: "ベオグラード",
    code: "rs",
    region: "europe",
  },
  {
    country: "Montenegro",
    capital: "Podgorica",
    capitalJP: "ポドゴリツァ",
    code: "me",
    region: "europe",
  },
  {
    country: "North Macedonia",
    capital: "Skopje",
    capitalJP: "スコピエ",
    code: "mk",
    region: "europe",
  },
  {
    country: "Romania",
    capital: "Bucharest",
    capitalJP: "ブカレスト",
    code: "ro",
    region: "europe",
  },
  {
    country: "Bulgaria",
    capital: "Sofia",
    capitalJP: "ソフィア",
    code: "bg",
    region: "europe",
  },
  {
    country: "Greece",
    capital: "Athens",
    capitalJP: "アテネ",
    code: "gr",
    region: "europe",
  },
  {
    country: "Albania",
    capital: "Tirana",
    capitalJP: "ティラナ",
    code: "al",
    region: "europe",
  },
  {
    country: "Moldova",
    capital: "Chișinău",
    capitalJP: "キシナウ",
    code: "md",
    region: "europe",
  },
  {
    country: "Ukraine",
    capital: "Kyiv",
    capitalJP: "キーウ",
    code: "ua",
    region: "europe",
  },
  {
    country: "Belarus",
    capital: "Minsk",
    capitalJP: "ミンスク",
    code: "by",
    region: "europe",
  },
  {
    country: "Lithuania",
    capital: "Vilnius",
    capitalJP: "ヴィリニュス",
    code: "lt",
    region: "europe",
  },
  {
    country: "Latvia",
    capital: "Riga",
    capitalJP: "リガ",
    code: "lv",
    region: "europe",
  },
  {
    country: "Estonia",
    capital: "Tallinn",
    capitalJP: "タリン",
    code: "ee",
    region: "europe",
  },
  {
    country: "Russia",
    capital: "Moscow",
    capitalJP: "モスクワ",
    code: "ru",
    region: "europe",
  },
  {
    country: "Andorra",
    capital: "Andorra la Vella",
    capitalJP: "アンドラ・ラ・ベリャ",
    code: "ad",
    region: "europe",
  },
  {
    country: "Monaco",
    capital: "Monaco",
    capitalJP: "モナコ",
    code: "mc",
    region: "europe",
  },
  {
    country: "Liechtenstein",
    capital: "Vaduz",
    capitalJP: "ファドゥーツ",
    code: "li",
    region: "europe",
  },
  {
    country: "San Marino",
    capital: "San Marino",
    capitalJP: "サンマリノ",
    code: "sm",
    region: "europe",
  },
  {
    country: "Vatican City",
    capital: "Vatican City",
    capitalJP: "バチカン市国",
    code: "va",
    region: "europe",
  },

  /* ===== AFRICA（54）===== */
  {
    country: "Egypt",
    capital: "Cairo",
    capitalJP: "カイロ",
    code: "eg",
    region: "africa",
  },
  {
    country: "Libya",
    capital: "Tripoli",
    capitalJP: "トリポリ",
    code: "ly",
    region: "africa",
  },
  {
    country: "Tunisia",
    capital: "Tunis",
    capitalJP: "チュニス",
    code: "tn",
    region: "africa",
  },
  {
    country: "Algeria",
    capital: "Algiers",
    capitalJP: "アルジェ",
    code: "dz",
    region: "africa",
  },
  {
    country: "Morocco",
    capital: "Rabat",
    capitalJP: "ラバト",
    code: "ma",
    region: "africa",
  },
  {
    country: "Sudan",
    capital: "Khartoum",
    capitalJP: "ハルツーム",
    code: "sd",
    region: "africa",
  },
  {
    country: "South Sudan",
    capital: "Juba",
    capitalJP: "ジュバ",
    code: "ss",
    region: "africa",
  },
  {
    country: "Ethiopia",
    capital: "Addis Ababa",
    capitalJP: "アディスアベバ",
    code: "et",
    region: "africa",
  },
  {
    country: "Eritrea",
    capital: "Asmara",
    capitalJP: "アスマラ",
    code: "er",
    region: "africa",
  },
  {
    country: "Djibouti",
    capital: "Djibouti",
    capitalJP: "ジブチ",
    code: "dj",
    region: "africa",
  },
  {
    country: "Somalia",
    capital: "Mogadishu",
    capitalJP: "モガディシュ",
    code: "so",
    region: "africa",
  },
  {
    country: "Kenya",
    capital: "Nairobi",
    capitalJP: "ナイロビ",
    code: "ke",
    region: "africa",
  },
  {
    country: "Uganda",
    capital: "Kampala",
    capitalJP: "カンパラ",
    code: "ug",
    region: "africa",
  },
  {
    country: "Rwanda",
    capital: "Kigali",
    capitalJP: "キガリ",
    code: "rw",
    region: "africa",
  },
  {
    country: "Burundi",
    capital: "Gitega",
    capitalJP: "ギテガ",
    code: "bi",
    region: "africa",
  },
  {
    country: "Tanzania",
    capital: "Dodoma",
    capitalJP: "ドドマ",
    code: "tz",
    region: "africa",
  },
  {
    country: "DR Congo",
    capital: "Kinshasa",
    capitalJP: "キンシャサ",
    code: "cd",
    region: "africa",
  },
  {
    country: "Republic of the Congo",
    capital: "Brazzaville",
    capitalJP: "ブラザヴィル",
    code: "cg",
    region: "africa",
  },
  {
    country: "Gabon",
    capital: "Libreville",
    capitalJP: "リーブルヴィル",
    code: "ga",
    region: "africa",
  },
  {
    country: "Equatorial Guinea",
    capital: "Malabo",
    capitalJP: "マラボ",
    code: "gq",
    region: "africa",
  },
  {
    country: "Cameroon",
    capital: "Yaoundé",
    capitalJP: "ヤウンデ",
    code: "cm",
    region: "africa",
  },
  {
    country: "Central African Republic",
    capital: "Bangui",
    capitalJP: "バンギ",
    code: "cf",
    region: "africa",
  },
  {
    country: "Chad",
    capital: "N'Djamena",
    capitalJP: "ンジャメナ",
    code: "td",
    region: "africa",
  },
  {
    country: "Nigeria",
    capital: "Abuja",
    capitalJP: "アブジャ",
    code: "ng",
    region: "africa",
  },
  {
    country: "Niger",
    capital: "Niamey",
    capitalJP: "ニアメ",
    code: "ne",
    region: "africa",
  },
  {
    country: "Mali",
    capital: "Bamako",
    capitalJP: "バマコ",
    code: "ml",
    region: "africa",
  },
  {
    country: "Burkina Faso",
    capital: "Ouagadougou",
    capitalJP: "ワガドゥグ",
    code: "bf",
    region: "africa",
  },
  {
    country: "Senegal",
    capital: "Dakar",
    capitalJP: "ダカール",
    code: "sn",
    region: "africa",
  },
  {
    country: "Gambia",
    capital: "Banjul",
    capitalJP: "バンジュール",
    code: "gm",
    region: "africa",
  },
  {
    country: "Guinea",
    capital: "Conakry",
    capitalJP: "コナクリ",
    code: "gn",
    region: "africa",
  },
  {
    country: "Guinea-Bissau",
    capital: "Bissau",
    capitalJP: "ビサウ",
    code: "gw",
    region: "africa",
  },
  {
    country: "Sierra Leone",
    capital: "Freetown",
    capitalJP: "フリータウン",
    code: "sl",
    region: "africa",
  },
  {
    country: "Liberia",
    capital: "Monrovia",
    capitalJP: "モンロビア",
    code: "lr",
    region: "africa",
  },
  {
    country: "Côte d'Ivoire",
    capital: "Yamoussoukro",
    capitalJP: "ヤムスークロ",
    code: "ci",
    region: "africa",
  },
  {
    country: "Ghana",
    capital: "Accra",
    capitalJP: "アクラ",
    code: "gh",
    region: "africa",
  },
  {
    country: "Togo",
    capital: "Lomé",
    capitalJP: "ロメ",
    code: "tg",
    region: "africa",
  },
  {
    country: "Benin",
    capital: "Porto-Novo",
    capitalJP: "ポルトノボ",
    code: "bj",
    region: "africa",
  },
  {
    country: "Cape Verde",
    capital: "Praia",
    capitalJP: "プライア",
    code: "cv",
    region: "africa",
  },
  {
    country: "South Africa",
    capital: "Pretoria",
    capitalJP: "プレトリア",
    code: "za",
    region: "africa",
  },
  {
    country: "Lesotho",
    capital: "Maseru",
    capitalJP: "マセル",
    code: "ls",
    region: "africa",
  },
  {
    country: "Eswatini",
    capital: "Mbabane",
    capitalJP: "ムババネ",
    code: "sz",
    region: "africa",
  },
  {
    country: "Botswana",
    capital: "Gaborone",
    capitalJP: "ガボローネ",
    code: "bw",
    region: "africa",
  },
  {
    country: "Zimbabwe",
    capital: "Harare",
    capitalJP: "ハラレ",
    code: "zw",
    region: "africa",
  },
  {
    country: "Zambia",
    capital: "Lusaka",
    capitalJP: "ルサカ",
    code: "zm",
    region: "africa",
  },
  {
    country: "Mozambique",
    capital: "Maputo",
    capitalJP: "マプト",
    code: "mz",
    region: "africa",
  },
  {
    country: "Malawi",
    capital: "Lilongwe",
    capitalJP: "リロングウェ",
    code: "mw",
    region: "africa",
  },
  {
    country: "Namibia",
    capital: "Windhoek",
    capitalJP: "ウィントフック",
    code: "na",
    region: "africa",
  },
  {
    country: "Angola",
    capital: "Luanda",
    capitalJP: "ルアンダ",
    code: "ao",
    region: "africa",
  },
  {
    country: "Sao Tome and Principe",
    capital: "São Tomé",
    capitalJP: "サントメ",
    code: "st",
    region: "africa",
  },
  {
    country: "Seychelles",
    capital: "Victoria",
    capitalJP: "ヴィクトリア",
    code: "sc",
    region: "africa",
  },
  {
    country: "Mauritius",
    capital: "Port Louis",
    capitalJP: "ポートルイス",
    code: "mu",
    region: "africa",
  },
  {
    country: "Comoros",
    capital: "Moroni",
    capitalJP: "モロニ",
    code: "km",
    region: "africa",
  },
  {
    country: "Madagascar",
    capital: "Antananarivo",
    capitalJP: "アンタナナリボ",
    code: "mg",
    region: "africa",
  },
  {
    country: "Mauritania",
    capital: "Nouakchott",
    capitalJP: "ヌアクショット",
    code: "mr",
    region: "africa",
  },

  /* ===== AMERICAS（35）===== */
  {
    country: "Canada",
    capital: "Ottawa",
    capitalJP: "オタワ",
    code: "ca",
    region: "americas",
  },
  {
    country: "United States",
    capital: "Washington, D.C.",
    capitalJP: "ワシントンD.C.",
    code: "us",
    region: "americas",
  },
  {
    country: "Mexico",
    capital: "Mexico City",
    capitalJP: "メキシコシティ",
    code: "mx",
    region: "americas",
  },
  {
    country: "Guatemala",
    capital: "Guatemala City",
    capitalJP: "グアテマラシティ",
    code: "gt",
    region: "americas",
  },
  {
    country: "Belize",
    capital: "Belmopan",
    capitalJP: "ベルモパン",
    code: "bz",
    region: "americas",
  },
  {
    country: "Honduras",
    capital: "Tegucigalpa",
    capitalJP: "テグシガルパ",
    code: "hn",
    region: "americas",
  },
  {
    country: "El Salvador",
    capital: "San Salvador",
    capitalJP: "サンサルバドル",
    code: "sv",
    region: "americas",
  },
  {
    country: "Nicaragua",
    capital: "Managua",
    capitalJP: "マナグア",
    code: "ni",
    region: "americas",
  },
  {
    country: "Costa Rica",
    capital: "San José",
    capitalJP: "サンホセ",
    code: "cr",
    region: "americas",
  },
  {
    country: "Panama",
    capital: "Panama City",
    capitalJP: "パナマシティ",
    code: "pa",
    region: "americas",
  },
  {
    country: "Cuba",
    capital: "Havana",
    capitalJP: "ハバナ",
    code: "cu",
    region: "americas",
  },
  {
    country: "Jamaica",
    capital: "Kingston",
    capitalJP: "キングストン",
    code: "jm",
    region: "americas",
  },
  {
    country: "Haiti",
    capital: "Port-au-Prince",
    capitalJP: "ポルトープランス",
    code: "ht",
    region: "americas",
  },
  {
    country: "Dominican Republic",
    capital: "Santo Domingo",
    capitalJP: "サントドミンゴ",
    code: "do",
    region: "americas",
  },
  {
    country: "Bahamas",
    capital: "Nassau",
    capitalJP: "ナッソー",
    code: "bs",
    region: "americas",
  },
  {
    country: "Barbados",
    capital: "Bridgetown",
    capitalJP: "ブリッジタウン",
    code: "bb",
    region: "americas",
  },
  {
    country: "Grenada",
    capital: "St. George's",
    capitalJP: "セントジョージズ",
    code: "gd",
    region: "americas",
  },
  {
    country: "Saint Lucia",
    capital: "Castries",
    capitalJP: "カストリーズ",
    code: "lc",
    region: "americas",
  },
  {
    country: "Saint Vincent and the Grenadines",
    capital: "Kingstown",
    capitalJP: "キングスタウン",
    code: "vc",
    region: "americas",
  },
  {
    country: "Saint Kitts and Nevis",
    capital: "Basseterre",
    capitalJP: "バステール",
    code: "kn",
    region: "americas",
  },
  {
    country: "Trinidad and Tobago",
    capital: "Port of Spain",
    capitalJP: "ポートオブスペイン",
    code: "tt",
    region: "americas",
  },
  {
    country: "Colombia",
    capital: "Bogotá",
    capitalJP: "ボゴタ",
    code: "co",
    region: "americas",
  },
  {
    country: "Venezuela",
    capital: "Caracas",
    capitalJP: "カラカス",
    code: "ve",
    region: "americas",
  },
  {
    country: "Guyana",
    capital: "Georgetown",
    capitalJP: "ジョージタウン",
    code: "gy",
    region: "americas",
  },
  {
    country: "Suriname",
    capital: "Paramaribo",
    capitalJP: "パラマリボ",
    code: "sr",
    region: "americas",
  },
  {
    country: "Ecuador",
    capital: "Quito",
    capitalJP: "キト",
    code: "ec",
    region: "americas",
  },
  {
    country: "Peru",
    capital: "Lima",
    capitalJP: "リマ",
    code: "pe",
    region: "americas",
  },
  {
    country: "Brazil",
    capital: "Brasília",
    capitalJP: "ブラジリア",
    code: "br",
    region: "americas",
  },
  {
    country: "Bolivia",
    capital: "Sucre",
    capitalJP: "スクレ",
    code: "bo",
    region: "americas",
  },
  {
    country: "Paraguay",
    capital: "Asunción",
    capitalJP: "アスンシオン",
    code: "py",
    region: "americas",
  },
  {
    country: "Uruguay",
    capital: "Montevideo",
    capitalJP: "モンテビデオ",
    code: "uy",
    region: "americas",
  },
  {
    country: "Argentina",
    capital: "Buenos Aires",
    capitalJP: "ブエノスアイレス",
    code: "ar",
    region: "americas",
  },
  {
    country: "Chile",
    capital: "Santiago",
    capitalJP: "サンティアゴ",
    code: "cl",
    region: "americas",
  },

  /* ===== OCEANIA（13）===== */
  {
    country: "Australia",
    capital: "Canberra",
    capitalJP: "キャンベラ",
    code: "au",
    region: "oceania",
  },
  {
    country: "New Zealand",
    capital: "Wellington",
    capitalJP: "ウェリントン",
    code: "nz",
    region: "oceania",
  },
  {
    country: "Papua New Guinea",
    capital: "Port Moresby",
    capitalJP: "ポートモレスビー",
    code: "pg",
    region: "oceania",
  },
  {
    country: "Solomon Islands",
    capital: "Honiara",
    capitalJP: "ホニアラ",
    code: "sb",
    region: "oceania",
  },
  {
    country: "Fiji",
    capital: "Suva",
    capitalJP: "スバ",
    code: "fj",
    region: "oceania",
  },
  {
    country: "Vanuatu",
    capital: "Port Vila",
    capitalJP: "ポートヴィラ",
    code: "vu",
    region: "oceania",
  },
  {
    country: "Samoa",
    capital: "Apia",
    capitalJP: "アピア",
    code: "ws",
    region: "oceania",
  },
  {
    country: "Tonga",
    capital: "Nukuʻalofa",
    capitalJP: "ヌクアロファ",
    code: "to",
    region: "oceania",
  },
  {
    country: "Kiribati",
    capital: "Tarawa",
    capitalJP: "タラワ",
    code: "ki",
    region: "oceania",
  },
  {
    country: "Tuvalu",
    capital: "Funafuti",
    capitalJP: "フナフティ",
    code: "tv",
    region: "oceania",
  },
  {
    country: "Nauru",
    capital: "Yaren",
    capitalJP: "ヤレン",
    code: "nr",
    region: "oceania",
  },
  {
    country: "Micronesia",
    capital: "Palikir",
    capitalJP: "パリキール",
    code: "fm",
    region: "oceania",
  },
  {
    country: "Marshall Islands",
    capital: "Majuro",
    capitalJP: "マジュロ",
    code: "mh",
    region: "oceania",
  },
];

window.countries = countries;
