// quiz/config/jodoushi-data.js
// 古典助動詞データ（jodoushi-typing / jodoushi-table 共用）
// quiz/index.html で両 config より先に読み込む。

window.JODOUSHI_DATA = [
  {
    name: "む",
    setsuzoku: "未然形",
    katsuyo: "四段型",
    imi: ["推量", "意志", "適当", "勧誘", "仮定", "婉曲"],
    mizen: "",
    renyo: "",
    shushi: "む",
    rentai: ["む", "ん"],
    izen: "め",
    meirei: "",
  },
  {
    name: "べし",
    setsuzoku: "終止形（ラ変は連体形）",
    katsuyo: "形容詞型",
    imi: ["推量", "意志", "可能", "当然", "命令", "適当"],
    mizen: "べかろ",
    renyo: ["べく", "べかり"],
    shushi: "べし",
    rentai: ["べき", "べかる"],
    izen: "べけれ",
    meirei: "",
  },
  {
    name: "まし",
    setsuzoku: "未然形",
    katsuyo: "特殊型",
    imi: ["反実仮想", "ためらいの意志"],
    mizen: "ましか",
    renyo: "",
    shushi: "まし",
    rentai: "まし",
    izen: "ましか",
    meirei: "",
  },
  {
    name: "じ",
    setsuzoku: "未然形",
    katsuyo: "無変化型",
    imi: ["打消推量", "打消意志"],
    mizen: "",
    renyo: "",
    shushi: "じ",
    rentai: "じ",
    izen: "",
    meirei: "",
  },
  {
    name: "まじ",
    setsuzoku: "終止形（ラ変は連体形）",
    katsuyo: "形容詞型",
    imi: ["打消推量", "打消意志", "打消当然", "不可能"],
    mizen: "まじかろ",
    renyo: ["まじく", "まじかり"],
    shushi: "まじ",
    rentai: ["まじき", "まじかる"],
    izen: "まじけれ",
    meirei: "",
  },
  {
    name: "ず",
    setsuzoku: "未然形",
    katsuyo: "特殊型",
    imi: "打消",
    mizen: ["ず", "ざら"],
    renyo: ["ず", "ざり"],
    shushi: "ず",
    rentai: ["ぬ", "ざる"],
    izen: ["ね", "ざれ"],
    meirei: "ざれ",
  },
  {
    name: "き",
    setsuzoku: "連用形",
    katsuyo: "特殊型",
    imi: "過去（直接体験）",
    mizen: "せ",
    renyo: "",
    shushi: "き",
    rentai: "し",
    izen: "しか",
    meirei: "",
  },
  {
    name: "けり",
    setsuzoku: "連用形",
    katsuyo: "ラ変型",
    imi: ["過去（間接体験）", "詠嘆"],
    mizen: "けら",
    renyo: "",
    shushi: "けり",
    rentai: "ける",
    izen: "けれ",
    meirei: "",
  },
  {
    name: "つ",
    setsuzoku: "連用形",
    katsuyo: "下二段型",
    imi: ["完了", "強意"],
    mizen: "て",
    renyo: "て",
    shushi: "つ",
    rentai: "つる",
    izen: "つれ",
    meirei: "てよ",
  },
  {
    name: "ぬ",
    setsuzoku: "連用形",
    katsuyo: "ナ変型",
    imi: ["完了", "強意"],
    mizen: "な",
    renyo: "に",
    shushi: "ぬ",
    rentai: "ぬる",
    izen: "ぬれ",
    meirei: "ね",
  },
  {
    name: "たり（完了）",
    setsuzoku: "連用形",
    katsuyo: "ラ変型",
    imi: ["完了", "存続"],
    mizen: "たら",
    renyo: ["たり", "て"],
    shushi: "たり",
    rentai: "たる",
    izen: "たれ",
    meirei: "たれ",
  },
  {
    name: "り",
    setsuzoku: ["サ変未然形", "四段已然形"],
    katsuyo: "ラ変型",
    imi: ["完了", "存続"],
    mizen: "ら",
    renyo: "り",
    shushi: "り",
    rentai: "る",
    izen: "れ",
    meirei: "れ",
  },
  {
    name: "らむ",
    setsuzoku: "終止形（ラ変は連体形）",
    katsuyo: "四段型",
    imi: ["現在推量", "原因推量", "伝聞", "婉曲"],
    mizen: "",
    renyo: "",
    shushi: "らむ",
    rentai: "らむ",
    izen: "らめ",
    meirei: "",
  },
  {
    name: "けむ",
    setsuzoku: "連用形",
    katsuyo: "四段型",
    imi: ["過去推量", "原因推量", "伝聞", "婉曲"],
    mizen: "",
    renyo: "",
    shushi: "けむ",
    rentai: "けむ",
    izen: "けめ",
    meirei: "",
  },
  {
    name: "なり（断定）",
    setsuzoku: ["体言", "連体形"],
    katsuyo: "ラ変型",
    imi: ["断定", "存在"],
    mizen: "なら",
    renyo: ["なり", "に"],
    shushi: "なり",
    rentai: "なる",
    izen: "なれ",
    meirei: "なれ",
  },
  {
    name: "なり（伝聞）",
    setsuzoku: "終止形（ラ変は連体形）",
    katsuyo: "ラ変型",
    imi: ["伝聞", "推定"],
    mizen: "",
    renyo: "なり",
    shushi: "なり",
    rentai: "なる",
    izen: "なれ",
    meirei: "",
  },
  {
    name: "たり（断定）",
    setsuzoku: "体言",
    katsuyo: "ラ変型",
    imi: "断定",
    mizen: "たら",
    renyo: ["たり", "と"],
    shushi: "たり",
    rentai: "たる",
    izen: "たれ",
    meirei: "たれ",
  },
  {
    name: ["す", "さす"],
    setsuzoku: "未然形",
    katsuyo: "下二段型",
    imi: ["使役", "尊敬"],
    mizen: ["せ", "させ"],
    renyo: ["せ", "させ"],
    shushi: ["す", "さす"],
    rentai: ["する", "さする"],
    izen: ["すれ", "さすれ"],
    meirei: ["せよ", "させよ"],
  },
  {
    name: "しむ",
    setsuzoku: "未然形",
    katsuyo: "下二段型",
    imi: ["使役", "尊敬"],
    mizen: "しめ",
    renyo: "しめ",
    shushi: "しむ",
    rentai: "しむる",
    izen: "しむれ",
    meirei: "しめよ",
  },
  {
    name: ["ゆ", "らゆ"],
    setsuzoku: "未然形",
    katsuyo: "下二段型",
    imi: ["受身", "自発", "可能", "尊敬"],
    mizen: ["ゆ", "らゆ"],
    renyo: ["ゆ", "らゆ"],
    shushi: ["ゆ", "らゆ"],
    rentai: ["ゆる", "らゆる"],
    izen: ["ゆれ", "らゆれ"],
    meirei: ["よ", "らよ"],
  },
];

window.JODOUSHI_COL_LABELS = {
  setsuzoku: "接続",
  katsuyo: "活用の種類",
  imi: "意味",
  mizen: "未然形",
  renyo: "連用形",
  shushi: "終止形",
  rentai: "連体形",
  izen: "已然形",
  meirei: "命令形",
};
