// china-data.js | 共通省データ
// eng は cn-atlas の feature.properties.name と照合するキー
// neighbors は eng キーで参照

const PROVINCES = [
  {
    eng: "Beijing",
    name: "北京市",
    reading: "ペキン",
    capital: "北京",
    population: 2189, // 万人（2020年）
    area: 1.64, // 万km²
    neighbors: ["Hebei", "Tianjin"],
    region: "华北",
  },
  {
    eng: "Tianjin",
    name: "天津市",
    reading: "テンシン",
    capital: "天津",
    population: 1387,
    area: 1.19,
    neighbors: ["Beijing", "Hebei"],
    region: "华北",
  },
  {
    eng: "Hebei",
    name: "河北省",
    reading: "カホク",
    capital: "石家庄",
    population: 7461,
    area: 18.85,
    neighbors: [
      "Beijing",
      "Tianjin",
      "Shanxi",
      "Inner Mongolia",
      "Liaoning",
      "Shandong",
      "Henan",
    ],
    region: "华北",
  },
  {
    eng: "Shanxi",
    name: "山西省",
    reading: "サンセイ",
    capital: "太原",
    population: 3492,
    area: 15.63,
    neighbors: ["Hebei", "Inner Mongolia", "Shaanxi", "Henan"],
    region: "华北",
  },
  {
    eng: "Inner Mongolia",
    name: "内モンゴル自治区",
    reading: "ないモンゴル",
    capital: "フフホト",
    population: 2404,
    area: 118.3,
    neighbors: [
      "Heilongjiang",
      "Jilin",
      "Liaoning",
      "Hebei",
      "Beijing",
      "Shanxi",
      "Shaanxi",
      "Ningxia",
      "Gansu",
      "Xinjiang",
    ],
    region: "华北",
  },
  {
    eng: "Liaoning",
    name: "遼寧省",
    reading: "リョウネイ",
    capital: "瀋陽",
    population: 4259,
    area: 14.75,
    neighbors: ["Inner Mongolia", "Jilin", "Hebei"],
    region: "东北",
  },
  {
    eng: "Jilin",
    name: "吉林省",
    reading: "キツリン",
    capital: "長春",
    population: 2407,
    area: 18.74,
    neighbors: ["Inner Mongolia", "Liaoning", "Heilongjiang"],
    region: "东北",
  },
  {
    eng: "Heilongjiang",
    name: "黒竜江省",
    reading: "コクリュウコウ",
    capital: "ハルビン",
    population: 3185,
    area: 47.35,
    neighbors: ["Inner Mongolia", "Jilin"],
    region: "东北",
  },
  {
    eng: "Shanghai",
    name: "上海市",
    reading: "シャンハイ",
    capital: "上海",
    population: 2487,
    area: 0.63,
    neighbors: ["Jiangsu", "Zhejiang"],
    region: "华东",
  },
  {
    eng: "Jiangsu",
    name: "江蘇省",
    reading: "コウソ",
    capital: "南京",
    population: 8475,
    area: 10.72,
    neighbors: ["Shanghai", "Zhejiang", "Anhui", "Shandong"],
    region: "华东",
  },
  {
    eng: "Zhejiang",
    name: "浙江省",
    reading: "セッコウ",
    capital: "杭州",
    population: 6457,
    area: 10.18,
    neighbors: ["Shanghai", "Jiangsu", "Anhui", "Jiangxi", "Fujian"],
    region: "华东",
  },
  {
    eng: "Anhui",
    name: "安徽省",
    reading: "アンキ",
    capital: "合肥",
    population: 6103,
    area: 13.97,
    neighbors: ["Jiangsu", "Zhejiang", "Jiangxi", "Hubei", "Henan", "Shandong"],
    region: "华东",
  },
  {
    eng: "Fujian",
    name: "福建省",
    reading: "フッケン",
    capital: "福州",
    population: 4154,
    area: 12.14,
    neighbors: ["Zhejiang", "Jiangxi", "Guangdong"],
    region: "华东",
  },
  {
    eng: "Jiangxi",
    name: "江西省",
    reading: "コウセイ",
    capital: "南昌",
    population: 4518,
    area: 16.69,
    neighbors: ["Anhui", "Zhejiang", "Fujian", "Guangdong", "Hunan", "Hubei"],
    region: "华东",
  },
  {
    eng: "Shandong",
    name: "山東省",
    reading: "サントウ",
    capital: "済南",
    population: 10153,
    area: 15.71,
    neighbors: ["Hebei", "Jiangsu", "Anhui", "Henan"],
    region: "华东",
  },
  {
    eng: "Henan",
    name: "河南省",
    reading: "カナン",
    capital: "鄭州",
    population: 9937,
    area: 16.7,
    neighbors: ["Hebei", "Shanxi", "Shaanxi", "Hubei", "Anhui", "Shandong"],
    region: "华中",
  },
  {
    eng: "Hubei",
    name: "湖北省",
    reading: "コホク",
    capital: "武漢",
    population: 5775,
    area: 18.59,
    neighbors: [
      "Henan",
      "Shaanxi",
      "Sichuan",
      "Chongqing",
      "Hunan",
      "Jiangxi",
      "Anhui",
    ],
    region: "华中",
  },
  {
    eng: "Hunan",
    name: "湖南省",
    reading: "コナン",
    capital: "長沙",
    population: 6644,
    area: 21.18,
    neighbors: [
      "Hubei",
      "Jiangxi",
      "Guangdong",
      "Guangxi",
      "Guizhou",
      "Chongqing",
    ],
    region: "华中",
  },
  {
    eng: "Guangdong",
    name: "広東省",
    reading: "カントン",
    capital: "広州",
    population: 12601,
    area: 17.97,
    neighbors: ["Fujian", "Jiangxi", "Hunan", "Guangxi"],
    region: "华南",
  },
  {
    eng: "Guangxi",
    name: "広西チワン族自治区",
    reading: "コウセイ",
    capital: "南寧",
    population: 5013,
    area: 23.67,
    neighbors: ["Guangdong", "Hunan", "Guizhou", "Yunnan"],
    region: "华南",
  },
  {
    eng: "Hainan",
    name: "海南省",
    reading: "カイナン",
    capital: "海口",
    population: 1008,
    area: 3.54,
    neighbors: [],
    region: "华南",
  },
  {
    eng: "Chongqing",
    name: "重慶市",
    reading: "チョンチン",
    capital: "重慶",
    population: 3205,
    area: 8.24,
    neighbors: ["Hubei", "Hunan", "Guizhou", "Sichuan", "Shaanxi"],
    region: "西南",
  },
  {
    eng: "Sichuan",
    name: "四川省",
    reading: "シセン",
    capital: "成都",
    population: 8367,
    area: 48.6,
    neighbors: [
      "Gansu",
      "Shaanxi",
      "Hubei",
      "Chongqing",
      "Guizhou",
      "Yunnan",
      "Tibet",
      "Qinghai",
    ],
    region: "西南",
  },
  {
    eng: "Guizhou",
    name: "貴州省",
    reading: "キシュウ",
    capital: "貴陽",
    population: 3856,
    area: 17.62,
    neighbors: ["Sichuan", "Chongqing", "Hunan", "Guangxi", "Yunnan"],
    region: "西南",
  },
  {
    eng: "Yunnan",
    name: "雲南省",
    reading: "ウンナン",
    capital: "昆明",
    population: 4720,
    area: 39.41,
    neighbors: ["Sichuan", "Guizhou", "Guangxi", "Tibet"],
    region: "西南",
  },
  {
    eng: "Tibet",
    name: "チベット自治区",
    reading: "チベット",
    capital: "ラサ",
    population: 365,
    area: 122.84,
    neighbors: ["Xinjiang", "Qinghai", "Sichuan", "Yunnan"],
    region: "西南",
  },
  {
    eng: "Shaanxi",
    name: "陝西省",
    reading: "センセイ",
    capital: "西安",
    population: 3953,
    area: 20.58,
    neighbors: [
      "Inner Mongolia",
      "Shanxi",
      "Henan",
      "Hubei",
      "Chongqing",
      "Sichuan",
      "Gansu",
      "Ningxia",
    ],
    region: "西北",
  },
  {
    eng: "Gansu",
    name: "甘粛省",
    reading: "カンシュク",
    capital: "蘭州",
    population: 2502,
    area: 42.59,
    neighbors: [
      "Inner Mongolia",
      "Ningxia",
      "Shaanxi",
      "Sichuan",
      "Qinghai",
      "Xinjiang",
    ],
    region: "西北",
  },
  {
    eng: "Qinghai",
    name: "青海省",
    reading: "セイカイ",
    capital: "西寧",
    population: 592,
    area: 72.23,
    neighbors: ["Xinjiang", "Gansu", "Sichuan", "Tibet"],
    region: "西北",
  },
  {
    eng: "Ningxia",
    name: "寧夏回族自治区",
    reading: "ネイカ",
    capital: "銀川",
    population: 720,
    area: 6.64,
    neighbors: ["Inner Mongolia", "Shaanxi", "Gansu"],
    region: "西北",
  },
  {
    eng: "Xinjiang",
    name: "新疆ウイグル自治区",
    reading: "シンキョウ",
    capital: "ウルムチ",
    population: 2585,
    area: 166.49,
    neighbors: ["Inner Mongolia", "Gansu", "Qinghai", "Tibet"],
    region: "西北",
  },
];

// cn-atlas で実際に使われている可能性のある名前の補正マップ
// ブラウザコンソールで feature.properties.name を確認してここを更新する
const ENG_NAME_FIX = {
  // "actual_geo_name": "PROVINCES.eng に対応するキー",
  // 例: "Xizang": "Tibet",
  Xizang: "Tibet",
  "Guangxi Zhuang": "Guangxi",
  "Nei Mongol": "Inner Mongolia",
  "Ningxia Hui": "Ningxia",
  "Xinjiang Uyghur": "Xinjiang",
};

const BY_ENG = Object.fromEntries(PROVINCES.map((p) => [p.eng, p]));

function resolveProvince(rawName) {
  if (BY_ENG[rawName]) return BY_ENG[rawName];
  const fixed = ENG_NAME_FIX[rawName];
  return fixed ? BY_ENG[fixed] : null;
}
